version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "api123"
      POSTGRES_DB: "practice"
    container_name: practice-container
    volumes:
      - ./postgres:/var/lib/postgresql/data
